---
- name: 'Load the OpenSSH OS-specific variables'
  ansible.builtin.include_vars: '{{ ansible_os_family }}.yml'

- name: 'Install OpenSSH'
  ansible.builtin.include_tasks: '{{ ansible_system }}/install.yml'

- name: 'Configure OpenSSH'
  ansible.builtin.include_tasks: '{{ ansible_system }}/configure.yml'
