---
- name: 'Include OS-specific variables'
  ansible.builtin.include_vars: '{{ ansible_os_family }}.yml'

- name: 'Include OS-specific tasks for Installing OpenSSH'
  ansible.builtin.include_tasks: '{{ ansible_system }}/install.yml'

- name: 'Include OS-specific tasks for Configure OpenSSH'
  ansible.builtin.include_tasks: '{{ ansible_system }}/configure.yml'
