---
- name: 'Include the OpenSSH OS-specific variables'
  ansible.builtin.include_vars: '{{ ansible_os_family }}.yml'

- name: 'Include tasks to install OpenSSH'
  ansible.builtin.include_tasks: '{{ ansible_system }}/install.yml'

- name: 'Include tasks to configure OpenSSH'
  ansible.builtin.include_tasks: '{{ ansible_system }}/configure.yml'
