---
- name: 'Linux | Restart SSHD'
  ansible.builtin.systemd:
    name: 'sshd'
    state: 'restarted'
  become: true

- name: 'Windows | Restart SSHD'
  ansible.windows.win_service:
    name: 'sshd'
    state: 'restarted'
