---
- name: 'Linux | Restart OpenSSH Server'
  ansible.builtin.systemd:
    name: 'sshd'
    state: 'restarted'
  when: not ansible_check_mode
  become: true

- name: 'Windows | Restart OpenSSH Server'
  ansible.windows.win_service:
    name: 'sshd'
    state: 'restarted'
