---
- name: 'Verify'
  hosts: all
  gather_facts: false
  tasks:
    - name: 'Check if OpenSSH Server is installed'
      ansible.windows.win_service:
        name: 'sshd'
      register: __sshd_service

    - name: 'Assert that OpenSSH Server is enabled and running'
      ansible.builtin.assert:
        that: "'running' in __sshd_service.state"
