---
- name: 'Linux | Configure and start OpenSSH'
  become: true
  block:
    - name: 'Linux | Ensure the OpenSSH is running and enabled at boot'
      ansible.builtin.systemd:
        name: 'sshd'
        state: 'started'
        enabled: true
      when: not ansible_check_mode

    - name: 'Linux | Configure OpenSSH server'
      ansible.builtin.template:
        src: 'sshd_config_Linux.j2'
        dest: '/etc/ssh/sshd_config'
        owner: 'root'
        group: 'root'
        mode: 0644
        validate: '/usr/sbin/sshd -T -C user=root -C host=localhost -C addr=localhost -f %s'
      notify: 'Linux | Restart SSHD'

    - name: 'Linux | Configure OpenSSH client'
      ansible.builtin.template:
        src: 'ssh_config_Linux.j2'
        dest: '/etc/ssh/ssh_config'
        owner: 'root'
        group: 'root'
        mode: 0644

- name: 'Linux | Configure SELinux when is already installed'
  when: ansible_selinux.status == 'enabled'
  become: true
  block:
    - name: 'Linux | Install SELinux required packages'
      ansible.builtin.package:
        name: "{{ ['policycoreutils-python']
          if ansible_python_version is version('3', '<')
          else ['policycoreutils-python-utils'] }}"
        state: 'present'

    - name: 'Linux | Allow SSHD port in SELinux'
      community.general.seport:
        ports: '{{ openssh_sshd_port }}'
        proto: 'tcp'
        setype: 'ssh_port_t'
        state: 'present'
