---
- name: 'Linux | Configure and start OpenSSH'
  block:
    - name: 'Linux | Configure OpenSSH Server'
      ansible.builtin.template:
        src: sshd_config_Linux.j2
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: 0644
        validate: /usr/sbin/sshd -T -C user=root -C host=localhost -C addr=localhost -f %s
      notify: Linux | Restart SSHD

    - name: 'Linux | Start OpenSSH Server'
      ansible.builtin.systemd:
        name: sshd
        enabled: true
        state: started

    - name: 'Linux | Configure OpenSSH Client'
      ansible.builtin.template:
        src: ssh_config_Linux.j2
        dest: /etc/ssh/ssh_config
        owner: root
        group: root
        mode: 0644
  become: true
