---

- name: 'Linux | Start OpenSSH Server'
  service:
    name: sshd
    enabled: true
    state: started

- name: 'Linux | Configure OpenSSH Server'
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600
    validate: /usr/sbin/sshd -T -C user=root -C host=localhost -C addr=localhost -f %s
  notify: Linux | Restart SSHD