---
- name: 'Linux | Configure SELinux when is already installed'
  when: ansible_selinux.status == 'enabled'
  become: true
  block:
    - name: 'Linux | Install SELinux required packages'
      ansible.builtin.package:
        name: "{{ ['policycoreutils-python']
          if ansible_python_version is version('3', '<')
          else ['policycoreutils-python-utils'] }}"
        state: present

    - name: 'Linux | Allow SSHD port in SELinux'
      seport:
        ports: '{{ openssh_sshd_port }}'
        proto: tcp
        setype: ssh_port_t
        state: present
