---
- name: 'Gathering Service Facts'
  ansible.builtin.service_facts:

- name: 'Linux | Configure SELinux when is already installed'
  block:
    - name: 'Linux | Install SELinux required packages'
      ansible.builtin.package:
        name: '{{ _openssh_selinux_packages }}'
        state: present

    - name: 'Linux | Allow SSHD port in SELinux'
      seport:
        ports: '{{ openssh_sshd_port }}'
        proto: tcp
        setype: ssh_port_t
        state: present
  when: ansible_selinux.status == 'enabled'
  become: true

- name: 'Linux | Allow SSHD port in FirewallD'
  firewalld:
    port: '{{ openssh_sshd_port }}/tcp'
    state: enabled
    permanent: true
    immediate: true
  when:
    - services['firewalld.service'] is defined
    - services['firewalld.service'].state == 'running'
  become: true
