---

- name: 'Linux | Configure SELinux when is already installed'
  block:
    - name: 'Linux | Install SELinux required packages'
      package:
        name: '{{ openssh__selinux_packages }}'
        state: present

    - name: 'Linux | Allow SSHD port in SELinux'
      seport:
        ports: '{{ openssh__sshd_port }}'
        proto: tcp
        setype: ssh_port_t
        state: present
  when: ansible_selinux.status == 'enabled'

- name: 'Linux | Allow SSHD port in FirewallD'
  firewalld:
    port: '{{ openssh__sshd_port }}/tcp'
    state: enabled
    permanent: true
    immediate: true
  when:
    - services['firewalld.service'] is defined
    - services['firewalld.service'].state == 'running'
