---
- name: 'Windows | Start OpenSSH Server'
  win_service:
    name: sshd
    start_mode: auto
    state: started

- name: 'Windows | Set Powershell as default shell'
  win_regedit:
    path: 'HKLM:\SOFTWARE\OpenSSH'
    name: DefaultShell
    data: 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
    type: string
    state: present

- name: 'Windows | Configure OpenSSH Server'
  win_template:
    src: sshd_config.j2
    dest: C:\ProgramData\ssh\sshd_config
  notify: Windows | Restart SSHD
