---
- name: 'Windows | Ensure the required NuGet package provider version is installed'
  win_shell: Find-PackageProvider -Name Nuget -ForceBootstrap -IncludeDependencies -Force
  failed_when: false
  changed_when: false

- name: 'Windows | Install required DSC modules'
  win_psmodule:
    name: '{{ item }}'
    repository: PSGallery
    accept_license: true
    state: present
  loop:
    - PowerShellGet
    - ComputerManagementDsc
    - NetworkingDsc

- name: 'Windows | Install OpenSSH packages'
  win_dsc:
    resource_name: WindowsCapability
    Name: '{{ item }}'
    Ensure: Present
  loop: '{{ _openssh_packages }}'
