---
- name: 'Windows | Ensure the required NuGet package provider version is installed'
  ansible.windows.win_shell: 'Find-PackageProvider -Name Nuget -ForceBootstrap -IncludeDependencies -Force'
  failed_when: false
  changed_when: false

- name: 'Windows | Install the required DSC modules'
  community.windows.win_psmodule:
    name: '{{ openssh_dsc_module }}'
    repository: 'PSGallery'
    accept_license: true
    state: 'present'
  loop:
    - 'PowerShellGet'
    - 'ComputerManagementDsc'
    - 'NetworkingDsc'
  loop_control:
    loop_var: openssh_dsc_module
  when: not ansible_check_mode

- name: 'Windows | Install OpenSSH packages'
  ansible.windows.win_dsc:
    resource_name: 'WindowsCapability'
    Name: '{{ openssh_package }}'
    Ensure: 'Present'
  loop: '{{ __openssh_packages }}'
  loop_control:
    loop_var: openssh_package
  when: not ansible_check_mode
